# Generated by Django 2.1.3 on 2018-11-22 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeClasse', models.DecimalField(decimal_places=0, max_digits=3)),
                ('annee', models.DecimalField(blank=True, choices=[(2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], decimal_places=0, max_digits=4)),
                ('session', models.TextField(choices=[('H', 'Hiver'), ('P', 'Printemps'), ('É', 'Été'), ('A', 'Automne')], max_length=10)),
                ('jourSemaine', models.TextField(choices=[('L', 'Lundi'), ('M', 'Mardi'), ('M', 'Mercredi'), ('J', 'Jeudi'), ('V', 'Vendredi')], max_length=10)),
                ('horaire', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeEnseignant', models.TextField(blank=True, max_length=500)),
                ('etudeMax', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codePerm', models.TextField(blank=True, max_length=500)),
                ('statut', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note1', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('note2', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('noteFinale', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('presence', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField(blank=True, max_length=500)),
                ('tel', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProgramme', models.TextField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSujet', models.TextField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('nbCredit', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('plan', models.TextField(blank=True, max_length=200)),
                ('bibliographie', models.TextField(blank=True, max_length=200)),
                ('preRequis', models.TextField(blank=True, max_length=200)),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SICAD.Programme')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='personne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SICAD.Personne'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='personne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SICAD.Personne'),
        ),
        migrations.AddField(
            model_name='classe',
            name='sujet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SICAD.Sujet'),
        ),
    ]
