# Generated by Django 2.1.3 on 2018-11-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SICAD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codePerm', models.TextField(blank=True, max_length=500)),
                ('statut', models.TextField(blank=True, max_length=500)),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SICAD.Personne')),
            ],
        ),
    ]
